In [1]:
import numpy as np

In [3]:
# Numpy naturalmente é mais eficiente que o Python quando se trata
# de lidar com números. Por mais que o mesmo pareça mais verboso em
# determinados momentos. Ele chega a ter de 5 a 100 vezes mais eficiência.
numpy_array = np.arange(0, 1_000 + 1, dtype='int64')

# Python lento para estas operações e alocação de memória
python_array = [i for i in range(1_000 + 1)]

In [4]:
# Entende naturalmente a sintaxe de i for i in X
numpy_square = numpy_array**2

# Ficou mais verboso que o numpy, por mais que inicialmente isto
# pareça melhor de ler do que a opção anterior.
python_square = [i**2 for i in python_array]

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(f"Array com: {arr}, tendo elementos do tipo: {arr.dtype} com tamanho de {arr.shape}")

# As propriedades utilizadas se referem ao "DataType" e ao "Formato do Array"
# Por ele ser somente um array em "linha", ele não possui o segundo número

Array com: [1 2 3 4 5], tendo elementos do tipo: int64 com tamanho de (5,)


In [ ]:
# Não irei demonstrar aqui, mas todos os meios de recortar arrays em Python
# utilizando [1:4:2], como [start:stop:step] continuam os mesmos.

In [14]:
# Criação de matrizes
matrix = np.arange(1.,10.).reshape(3,3)
print(f"O formato da matriz é de {matrix.shape}, três colunas e três linhas")
print(matrix)

O formato da matriz é de (3, 3), três colunas e três linhas
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [15]:
# Acessando a 2° linha do array
matrix_line = matrix[1]

# Acessando a 1° coluna
matrix_column = matrix[:, 0] 

print(matrix_line)
print(matrix_column)

[4. 5. 6.]
[1. 4. 7.]
